### checking if the server is live
GET http://localhost:8000/

# ================ USER API
### post new user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name": "Prem Acharay",
    "email": "a@a.com",
    "pin": 1234
}



# ================ TRANSACTION API
### get users transactions
GET  http://localhost:8000/api/v1/transaction
Authorization: 64cbb3208db8367ecbaf0f37

### add users transactions
POST   http://localhost:8000/api/v1/transaction
Content-Type: application/json
Authorization: 64cbb3208db8367ecbaf0f37

{
    "type": "expenses",
    "name" : "shopping",
    "amount": 44
}